### PR TITLE
Finish writing all stimulus layouts

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
While working on stimulus layout #4, I was able to generalize some logic for writing all the features of the csv files in an automated fashion.

Still a bit of code cleanup to do - also, the timestamps right now are not entirely synchronized for multiple segments, pointing back to the need to use the information extracted from accompanying `.nidq` files for this purpose (waiting on Alessio to debug).

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
Code now mostly cleaned up, waiting specifically on PR #15 to fully debug timestamp synchronization for multi-segment data.

**Comment by CodyCBakerPhD** [comment]
@bendichter This code is now ready for review, working well on the `210109` session data.

The parts involving `segment_trial_start_times` will likely have to be reworked slightly for the multi-segment `210406` data, but that would be a smaller follow-up PR depending on #16.

**Comment by CodyCBakerPhD** [comment]
Written trials table appears as follows

https://user-images.githubusercontent.com/51133164/126015053-094bc376-3dc9-4bc2-88c9-a813b8d6b6f0.mp4

There will be a couple tweaks on the to-do list to adjust the widgets to allow them to expand trials data, as well as better handling of the units table alignment times when a column of the Units table is indexed, but those are outside this PR and repo.

**Review by bendichter — APPROVED** [review]
LGTM!

**Pull request merged**
